// ─── BMA Park Manual Metadata ─────────────────────────────────────────────────
// Fill in the English name, description, and openHours for each park.
// Thai names (nameTh) are from the official Greener Bangkok API — do not change.
// Leave fields as "" if you don't have the info yet.

export interface ParkMeta {
  slug: string        // matches the WP API slug — do not change
  nameTh: string      // official Thai name — do not change
  nameEn: string      // ← FILL THIS IN
  description: string // ← FILL THIS IN (1-2 sentences in English)
  openHours: string   // ← FILL THIS IN e.g. "05:00–21:00" or "Open 24 hours"
}

export const BMA_PARKS_META: ParkMeta[] = [
  {
    slug: "suan-lumpini",
    nameTh: "สวนลุมพินี",
    nameEn: "Lumphini Park",
    description: "Bangkok's most iconic green space. 2.5 km lake loop, morning tai chi, evening joggers.",
    openHours: "04:30–21:00",
  },
  {
    slug: "benjakitti-park",
    nameTh: "สวนเบญจกิติ",
    nameEn: "Benjakitti Park",
    description: "Scenic lake park next to Queen Sirikit Convention Centre with a popular 1.8 km loop.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-wachirabenjathat-suan-rotfai",
    nameTh: "สวนวชิระเบญจทัศ (สวนรถไฟ)",
    nameEn: "Wachirabenchathat Park (Rot Fai)",
    description: "Large lake park in Dusit with a 3 km cycling and running track. Less crowded than Lumphini.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-chatuchak",
    nameTh: "สวนจตุจักร",
    nameEn: "Chatuchak Park",
    description: "Shaded park next to Chatuchak Weekend Market. Good 1.5 km loop, great for early morning runs.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-luang-r-9",
    nameTh: "สวนหลวง ร.9",
    nameEn: "Suan Luang Rama IX",
    description: "Bangkok's largest public park at 200 ha. Botanical gardens, long running paths, open spaces.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-luang-phra-ram-8",
    nameTh: "สวนหลวงพระราม 8",
    nameEn: "Suan Luang Rama VIII Park",
    description: "Riverside park along the Chao Phraya near Rama VIII Bridge. River breeze keeps air quality good.",
    openHours: "05:00–21:00",
  },
  {
    slug: "utthayan-benjasiri",
    nameTh: "อุทยานเบญจสิริ",
    nameEn: "Benjasiri Park",
    description: "Compact Sukhumvit park popular for yoga groups and evening walkers. Well shaded.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-somdet-phranangchao-sirikit",
    nameTh: "สวนสมเด็จพระนางเจ้าสิริกิติ์ฯ",
    nameEn: "Queen Sirikit Park",
    description: "Royal park in northern Bangkok near Chatuchak with large open lawns and a central lake.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-romanee-nat",
    nameTh: "สวนรมณีนาถ",
    nameEn: "Romaneenart Park",
    description: "Former prison turned public park on Rattanakosin island. Historical setting with shaded paths.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-saran-rom",
    nameTh: "สวนสารารมย์",
    nameEn: "Saranrom Park",
    description: "Historic royal garden near the Grand Palace. Elegant fountains and manicured lawns.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-santipap",
    nameTh: "สวนสันติภาพ",
    nameEn: "Santiphap Park",
    description: "Peace Park near Democracy Monument. Popular with local residents for morning exercise.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-satharana-sun-gi-la-bueng-nong-bon",
    nameTh: "สวนสาธารณะศูนย์กีฬาบึงหนองบ่อน",
    nameEn: "Nong Bon Sports Park",
    description: "Large lake park in eastern Bangkok with sports facilities and a scenic waterfront path.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-gi-la-ram-inthra",
    nameTh: "สวนกีฬารามอินทรา",
    nameEn: "Ram Indra Sports Park",
    description: "Sports-focused park in northern Bangkok with running tracks and outdoor fitness equipment.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-serithai",
    nameTh: "สวนเสรีไทย",
    nameEn: "Seri Thai Park",
    description: "Community park in eastern Bangkok with a large open field and shaded walking paths.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-pom-mahakala",
    nameTh: "สวนป้อมมหากาฬ",
    nameEn: "Mahakan Fort Park",
    description: "Historic park beside the old city wall and Mahakan Fort. Compact but charming green space.",
    openHours: "06:00–20:00",
  },
  {
    slug: "sanam-luang",
    nameTh: "สนามหลวง",
    nameEn: "Sanam Luang",
    description: "The grand royal field in front of the Grand Palace. Used for royal ceremonies and public events.",
    openHours: "Open 24 hours",
  },
  {
    slug: "suan-loi-fa-jao-phaya",
    nameTh: "สวนลอยฟ้าเจ้าพระยา",
    nameEn: "Chao Phraya Sky Park",
    description: "Elevated park bridge over the Chao Phraya River. Stunning river views and cool breezes.",
    openHours: "06:00–21:00",
  },
  {
    slug: "suan-nawamin-phiroam",
    nameTh: "สวนนวมินทร์ภิรมย์",
    nameEn: "Nawamin Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-tavee-wanarom",
    nameTh: "สวนทวีวนารมย์",
    nameEn: "Thawiwanarom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-tawe-kanchanaphisek",
    nameTh: "สวนทวีกาญจนาภิเษก",
    nameEn: "Thawe Kanchanaphisek Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-pranakorn",
    nameTh: "สวนพระนคร",
    nameEn: "Phra Nakhon Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-charanphiroam",
    nameTh: "สวนจรัญภิรมย์",
    nameEn: "Charan Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-bangkae-phiroam",
    nameTh: "สวนบางแคภิรมย์",
    nameEn: "Bang Khae Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-pa-wipavadi-rangsit",
    nameTh: "สวนป่าวิภาวดีรังสิต",
    nameEn: "Vibhavadi Forest Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-pa-prachaniwet-mubaan-prachaniwet",
    nameTh: "สวนป่าประชานิเวศน์ (หมู่บ้านประชานิเวศน์)",
    nameEn: "Prachaniwet Forest Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-sirindhorn-phreuksapan",
    nameTh: "สวนสิรินธราพฤกษาพรรณ",
    nameEn: "Sirindhorn Phrueksa Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-romanee-thung-seekan",
    nameTh: "สวนรมณีย์ทุ่งสีกัน",
    nameEn: "Romanee Thung Seekan Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-tian-thale-pattana-phrueksa-phiroam",
    nameTh: "สวนเทียนทะเลพัฒนาพฤกษ์ภิรมย์",
    nameEn: "Thian Thale Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-won-tham",
    nameTh: "สวนวนธรรม",
    nameEn: "Wontham Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-50-phansa-mahachakri-sirindhorn",
    nameTh: "สวน 50 พรรษา มหาจักรีสิรินธร",
    nameEn: "50th Birthday Princess Sirindhorn Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-watchara-phiroam",
    nameTh: "สวนวัชราภิรมย์",
    nameEn: "Watchara Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-wari-phiroam",
    nameTh: "สวนวารีภิรมย์",
    nameEn: "Wari Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-siri-phiroam-bueng-lam-phai",
    nameTh: "สวนสิริภิรมย์ (บึงลำไผ่)",
    nameEn: "Siri Phirom Park (Bueng Lam Phai)",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-praya-phiroam",
    nameTh: "สวนพระยาภิรมย์",
    nameEn: "Phraya Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-satharana-bueng-nam-ladphrao-71",
    nameTh: "สวนสาธารณะบึงน้ำลาดพร้าว 71",
    nameEn: "Lat Phrao 71 Pond Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-piya-phiroam",
    nameTh: "สวนปิยะภิรมย์",
    nameEn: "Piya Phirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-satharana-thang-tang-radap-thanon-phran-nok",
    nameTh: "สวนสาธารณะทางตัดระดับถนนพระนนก",
    nameEn: "Phran Nok Underpass Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-buengkratiem",
    nameTh: "สวนบึงกระเทียม",
    nameEn: "Bueng Kratiem Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-60-phansa-somdet-phranangchao-phra-borommarachininat",
    nameTh: "สวน 60 พรรษา สมเด็จพระบรมราชินีนาถ",
    nameEn: "Queen's 60th Birthday Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-somdet-ya-84",
    nameTh: "สวนสมเด็จย่า 84",
    nameEn: "Somdet Ya 84 Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-thanaburirom",
    nameTh: "สวนธนบุรีรมย์",
    nameEn: "Thanaburirom Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-pa-thang-tang-radap-ratchadapisek-wipavadi-rangsit",
    nameTh: "สวนป่าทางตัดระดับรัชดาภิเษก-วิภาวดีรังสิต",
    nameEn: "Ratchadaphisek-Vibhavadi Forest Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-chaloem-phra-kian-phra-bat-somdet-phra-jao-yu-hua-phra-chonnam-phansa-7-rop",
    nameTh: "สวนเฉลิมพระเกียรติพระบาทสมเด็จพระเจ้าอยู่หัว พระชนมพรรษา 7 รอบ",
    nameEn: "King's 7th Cycle Birthday Celebration Park",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-chaloem-phra-kian-80-phansa-phra-bat-somdet-phra-jao-yu-hua-sathorn",
    nameTh: "สวนเฉลิมพระเกียรติ 80 พรรษา พระบาทสมเด็จพระเจ้าอยู่หัว (สาทร)",
    nameEn: "King's 80th Birthday Park (Sathorn)",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-chaloem-phra-kian-80-phansa-phra-bat-somdet-phra-jao-yu-hua-bangkok-noi",
    nameTh: "สวนเฉลิมพระเกียรติ 80 พรรษา พระบาทสมเด็จพระเจ้าอยู่หัว (บางกอกน้อย)",
    nameEn: "King's 80th Birthday Park (Bangkok Noi)",
    description: "",
    openHours: "",
  },
  {
    slug: "lan-kon-mueang-bkk",
    nameTh: "ลานคนเมือง ศาลากลางกรุงเทพมหานคร",
    nameEn: "City Hall People's Square",
    description: "",
    openHours: "",
  },
  {
    slug: "suan-jak-phu-pha-su-mahanatee",
    nameTh: "สวนจากภูผาสู่มหานที",
    nameEn: "Jak Phu Pha Su Mahanatee Park",
    description: "",
    openHours: "",
  },
]

// Lookup by slug for fast access
export const BMA_META_BY_SLUG = Object.fromEntries(
  BMA_PARKS_META.map((p) => [p.slug, p])
)
