// ─── BMA Park Manual Metadata ─────────────────────────────────────────────────
// Fill in the English name, description, and openHours for each park.
// Thai names (nameTh) are from the official Greener Bangkok API — do not change.
// Leave fields as "" if you don't have the info yet.

export interface ParkMeta {
  slug: string        // matches the WP API slug — do not change
  nameTh: string      // official Thai name — do not change
  nameEn: string      // ← FILL THIS IN
  description: string // ← FILL THIS IN (1-2 sentences in English)
  openHours: string   // ← FILL THIS IN e.g. "05:00–21:00" or "Open 24 hours"
  fallbackCentroid?: [number, number] // [lat, lng] used when no OSM polygon match found
}

export const BMA_PARKS_META: ParkMeta[] = [
  {
    slug: "suan-lumpini",
    nameTh: "สวนลุมพินี",
    nameEn: "Lumphini Park",
    description: "Bangkok's first public park will turn 100 years old in 2025. It is not only a symbol of the city's central lungs with activity spaces for people of all ages, but also a place of historical, cultural and environmental value.",
    openHours: "04:30–22:00",
  },
  {
    slug: "benjakitti-park",
    nameTh: "สวนเบญจกิติ",
    nameEn: "Benjakitti Park",
    description: "A large forest park in the heart of the city, covering an area of 450 rai, which is not only a lung for city people to breathe, but also creates a complete natural ecosystem, conserving local plants, along with solving flooding and water pollution problems, under a design concept that creates a relationship for people, animals and nature to benefit each other.",
    openHours: "04:30–22:00",
  },
  {
    slug: "suan-wachirabenjathat-suan-rotfai",
    nameTh: "สวนวชิระเบญจทัศ (สวนรถไฟ)",
    nameEn: "Wachirabenchathat Park (Rot Fai)",
    description: "Welcome to the kingdom of happiness for everyone in the family, or as it is popularly known as “Suan Rot Fai”. In addition to the shady, cool and free feeling on a wide area of 375 rai, there are also many interesting activities for everyone in the family.",
    openHours: "04:30–21:00",
  },
  {
    slug: "suan-chatuchak",
    nameTh: "สวนจตุจักร",
    nameEn: "Chatuchak Park",
    description: "The first public park of Chatuchak Park, is a large public park in the shady, beautifully decorated business district, easy to travel to. It is also called Squirrel Park because there are many large trees. It is home to hundreds of squirrels that are very familiar with people. There is also a literary garden with trees from literature to see, such as the Paduak tree from the epic poem Khun Chang - Khun Phaen, the Anchan tree from the Kap Hor Klong Nirat Tharn Sok, and the Leb Mue Nang tree from the story of Inao, etc.",
    openHours: "4:30–22:00",
  },
  {
    slug: "suan-luang-r-9",
    nameTh: "สวนหลวง ร.9",
    nameEn: "Suan Luang Rama IX",
    description: "Experience the beauty, tranquility and lush greenery of the largest public park and botanical garden in Bangkok. With a spacious area of 500 rai, enjoy various species of plants, international gardens and conservation of life in the ecosystem.",
    openHours: "05:00–19:00",
  },
  {
    slug: "suan-luang-phra-ram-8",
    nameTh: "สวนหลวงพระราม 8",
    nameEn: "Suan Luang Rama VIII Park",
    description: "A nice park by the Chao Phraya River, shady and decorated with large and small trees in an orderly manner. It is a good place to exercise and enjoy the beautiful scenery. You can see many important historical sites of Rattanakosin Island.",
    openHours: "05:00–21:00",
  },
  {
    slug: "utthayan-benjasiri",
    nameTh: "อุทยานเบญจสิริ",
    nameEn: "Benjasiri Park",
    description: "A small public park in the heart of Bangkok, covering an area of 29 rai, there are 18 important sculptures by national artists, one of which is a commemorative coin in honor of Her Majesty the Queen, standing in full body, 3 meters in size, with a musical fountain show.",
    openHours: "04:30–22:00",
  },
  {
    slug: "suan-somdet-phranangchao-sirikit",
    nameTh: "สวนสมเด็จพระนางเจ้าสิริกิติ์ฯ",
    nameEn: "Queen Sirikit Park",
    description: "One of the most complete botanical gardens in Thailand, it contains over 2,000 species of plants and has many places to relax, including a pond shaped like the letter “S” and “S”, which is highlighted by the yellow color of the royal trumpet tree flowers and the purple-pink color of the indigo flowers, as well as a large lotus lawn.",
    openHours: "05:00–19:00",
  },
  {
    slug: "suan-ramani-nat",
    nameTh: "สวนรมณีนาถ",
    nameEn: "Ramani nat Park",
    description: "From a prison over 100 years old, popularly known as “Old Prison”, it has been transformed into a public park and health park in the city center for people of all ages to pay homage to Her Majesty Queen Sirikit on the occasion of her 60th birthday and is an ancient site in the same place.",
    openHours: "04:00–21:00",
  },
  {
    slug: "suan-saran-rom",
    nameTh: "สวนสารารมย์",
    nameEn: "Saranrom Park",
    description: "Saranrom Park or Saranrom Royal Park is a public park with a history dating back centuries. It used to be the residence of the royal family and a place to welcome foreign royal guests during the reign of King Rama V. It is currently a popular exercise spot for both Thais and foreigners. It is imbued with art and culture and reflects the Thai gardens of the Rattanakosin period that were influenced by Western civilization.",
    openHours: "04:00–21:00",
  },
  {
    slug: "suan-santipap",
    nameTh: "สวนสันติภาพ",
    nameEn: "Santiphap Park",
    description: "A park in the concept of a forest park in the middle of the city that is peaceful and cool with a forest around the park and only necessary buildings. It is a natural area where families often come to sit, listen to music and relax in the evenings. This is the origin of the music park.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-satharana-sun-gi-la-bueng-nong-bon",
    nameTh: "สวนสาธารณะศูนย์กีฬาบึงหนองบ่อน",
    nameEn: "Nong Bon Sports Park",
    description: "Welcome to the largest public park in Bangkok covering an area of over 644 rai, with a large lake as a landmark and a water sports center suitable for both professionals and amateurs, and also offers lessons for those interested.",
    openHours: "04:30–18:30",
    fallbackCentroid: [13.6912, 100.6478],
  },
  {
    slug: "suan-gi-la-ram-inthra",
    nameTh: "สวนกีฬารามอินทรา",
    nameEn: "Ram Indra Sports Park",
    description: "A park for fitness lovers hidden in a forest park, it is not only outstanding with a walking-running path on a small hill-like hill, which is the origin of its other name, “Mountain Park”, in a cool atmosphere, but also has a variety of standard sports fields.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-serithai",
    nameTh: "สวนเสรีไทย",
    nameEn: "Seri Thai Park",
    description: "Seri Thai Park or Bueng Kum Water Park in its original name is a large old public park with a large pond from the royal initiative project of King Rama IX to receive rainwater from the eastern part of Bangkok, solving the flooding problem at that time. It has become the park's identity amidst a peaceful and shady atmosphere even during the day.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-pom-mahakala",
    nameTh: "สวนป้อมมหากาฬ",
    nameEn: "Mahakan Fort Park",
    description: "The historical area as a community on the outskirts of the city wall, the only remaining one in Rattanakosin Island, has been developed into a public park for relaxation, exercise and historical learning.",
    openHours: "05:00–21:00",
  },
  {
    slug: "sanam-luang",
    nameTh: "สนามหลวง",
    nameEn: "Sanam Luang",
    description: "A large field that used to be a royal cremation field, rice fields, a kite flying field, a golf course, a flea market, and a symbolic area for important ceremonies and events. It is not only a historical and cultural site, but also one of the first public spaces in Bangkok.",
    openHours: "05:00–22:00",
  },
  {
    slug: "suan-loi-fa-jao-phaya",
    nameTh: "สวนลอยฟ้าเจ้าพระยา",
    nameEn: "Chao Phraya Sky Park",
    description: "Elevated park bridge over the Chao Phraya River. Stunning river views and cool breezes.",
    openHours: "05:00–20:00",
  },
  {
    slug: "suan-nawamin-phiroam",
    nameTh: "สวนนวมินทร์ภิรมย์",
    nameEn: "Nawamin Phirom Park",
    description: "A multi-purpose public park around the Khlong Chan Lake (Bueng Lamphang Phue), shady with large trees and a fountain in the middle of the lake, adding a refreshing and cool atmosphere. It is another public park where many people come to exercise.",
    openHours: "04.30-21.00",
  },
  {
    slug: "suan-tavee-wanarom",
    nameTh: "สวนทวีวนารมย์",
    nameEn: "Thawiwanarom Park",
    description: "A public park and activity center on the Thonburi side, which is shady and beautiful with ornamental flowers. It is divided into 2 zones: a public park zone and a coconut grove zone, which are connected by a bridge.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-thawee-kanchanaphisek",
    nameTh: "สวนทวีกาญจนาภิเษก",
    nameEn: "Thawee Kanchanaphisek Park",
    description: "A new public park in Bangkok on Kanchanaphisek Road, a place for relaxation, walking, running and exercising in a relaxed atmosphere, not crowded.",
    openHours: "open 24 hours",
    fallbackCentroid: [13.7573, 100.3938],
  },
  {
    slug: "suan-pranakorn",
    nameTh: "สวนพระนคร",
    nameEn: "Phra Nakhon Park",
    description: "A small green space for city people, also known as “Suan Lat Krabang”, has a unique garden of bonsai trees in the shape of various animals in various poses, in addition to the shady and beautiful nature, suitable for walking and exercising.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-charanphiroam",
    nameTh: "สวนจรัญภิรมย์",
    nameEn: "Charan Phirom Park",
    description: "A small village park for relaxation, exercise and adding green space to Bang Phlat District.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.7816, 100.4718],
  },
  {
    slug: "suan-bangkae-phiroam",
    nameTh: "สวนบางแคภิรมย์",
    nameEn: "Bang Khae Phirom Park",
    description: "The park under the concept of “ASEAN Community Park” is not only the first park in Bang Khae District, but also the second park in Bangkok that has a dog park with many facilities for relaxation and exercise.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-pa-wipavadi-rangsit",
    nameTh: "สวนป่าวิภาวดีรังสิต",
    nameEn: "Vibhavadi Forest Park",
    description: "A recreational park in Din Daeng area, shady with tall trees, another green space in Bangkok where you can take your dog for a relaxing walk. However, you may need to take extra care because it is located on a main road.",
    openHours: "open 24 hours",
  },
  {
    slug: "suan-pa-prachaniwet-mubaan-prachaniwet",
    nameTh: "สวนป่าประชานิเวศน์ (หมู่บ้านประชานิเวศน์)",
    nameEn: "Prachaniwet Forest Park",
    description: "A small garden on an area of 10 rai, with a shady atmosphere, green with rain trees, ornamental plants and lawns. It is a place for relaxation, exercise and activity for people in Prachaniwet Village.",
    openHours: "open 24 hours",
  },
  {
    slug: "suan-sirindhorn-phreuksapan",
    nameTh: "สวนสิรินธราพฤกษาพรรณ",
    nameEn: "Sirindhorn Phrueksa Park",
    description: "The public park reflects the culture of Bang Khun Non, which still preserves the original garden characteristics as much as possible, including the raised garden style to store water for use, rare plant species planted in the original area, and old wooden houses.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.8514, 100.5638],
  },
  {
    slug: "suan-romanee-thung-sikan",
    nameTh: "สวนรมณีย์ทุ่งสีกัน",
    nameEn: "Romanee Thung Sikan Park",
    description: "A small public park that used to be a forest park with greenery and trees. It is characterized by its unique Thai-style buildings and pavilions. It is suitable for relaxation, exercise, and organizing activities on various occasions.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-tian-thale-pattana-phrueksa-phiroam",
    nameTh: "สวนเทียนทะเลพัฒนาพฤกษ์ภิรมย์",
    nameEn: "Thian Thale Park",
    description: "A new public park in Bang Khun Thian area, just opened for 2 years, is part of Bangkok's Green Bangkok 2030 project, which not only increases green space for city dwellers, but is also an ecological mangrove park and a dog park.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-wana-thum",
    nameTh: "สวนวนธรรม",
    nameEn: "Wana Thum Park",
    description: "The first garden in Bangkok with a design concept based on the teachings of the Lord Buddha. There is a meditation area under the shade of trees related to Buddhism. It is a garden of Dharma where you can relax your mind and feel the scent of Dharma and nature.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-50-phansa-mahachakri-sirindhorn",
    nameTh: "สวน 50 พรรษา มหาจักรีสิรินธร",
    nameEn: "50th Birthday Princess Sirindhorn Park",
    description: "A small public park in the middle of the Maha Thai community and near Ramkhamhaeng University 2, which focuses on supporting the services of the surrounding people, both for exercise and a shady and refreshing place for relaxation with various types of plants and a large pond.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-watchara-phiroam",
    nameTh: "สวนวัชราภิรมย์",
    nameEn: "Watchara Phirom Park",
    description: "A park under the Ram Intra Expressway with the concept of creating a city that is friendly to pets. In addition to being a place for relaxation, exercise and recreational activities amidst the pleasant nature, it is also the first dog park under the responsibility of the Bangkok Metropolitan Administration.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-wari-phiroam",
    nameTh: "สวนวารีภิรมย์",
    nameEn: "Wari Phirom Park",
    description: "A natural kingdom in the suburbs with an atmosphere like being in the countryside, both in terms of scenery, air and way of life, or also known as Bueng Makham Thet or Bueng Sakae Ngam Sam Duan, there are many activities suitable for all ages, especially bicycle paths that have all forms, from normal lanes to off-road roads.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.7450, 100.4812],
  },
  {
    slug: "suan-siri-phiroam-bueng-lam-phai",
    nameTh: "สวนสิริภิรมย์ (บึงลำไผ่)",
    nameEn: "Siri Phirom Park (Bueng Lam Phai)",
    description: "A public park that combines a botanical garden and a natural classroom about various plants. In addition to being a multi-purpose park for everyone in the family, there is an area for young children to relax and exercise.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.7286, 100.7352],
  },
  {
    slug: "suan-praya-phiroam",
    nameTh: "สวนพระยาภิรมย์",
    nameEn: "Phraya Phirom Park",
    description: "A small public park surrounded by large trees. It is a place for relaxation, exercise, organizing recreational activities and learning about nature. It increases green space and improves the quality of life of city people.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.8062, 100.5392],
  },
  {
    slug: "suan-satharana-bueng-nam-ladphrao-71",
    nameTh: "สวนสาธารณะบึงน้ำลาดพร้าว 71",
    nameEn: "Lat Phrao 71 Pond Park",
    description: "Floating Garden, a place for relaxation and exercise on an area of 21 rai in the heart of Lat Phrao, but the highlight is the floating artificial grass field for children to release their energy in the middle of a large pond.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-piya-phiroam",
    nameTh: "สวนปิยะภิรมย์",
    nameEn: "Piya Phirom Park",
    description: "A small green space in the heart of the city, Bang Kapi District, with an area of less than 12 rai, but perfectly suited to the form of a health park and community activity area, suitable for use by the whole family.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-satharana-thang-tang-radap-thanon-phran-nok",
    nameTh: "สวนสาธารณะทางตัดระดับถนนพระนนก",
    nameEn: "Phran Nok Underpass Park",
    description: "From the vacant area under the expressway, it has been renovated into a 46-rai public park, which is the first Pet Friendly Park in Bangkok. Pets are allowed to use the service without any restrictions, but must comply with the terms and conditions for using the service.",
    openHours: "open 24 hours",
    fallbackCentroid: [13.7559, 100.4637],
  },
  {
    slug: "suan-buengkratiem",
    nameTh: "สวนบึงกระเทียม",
    nameEn: "Bueng Kratiem Park",
    description: "A public park by the lake, 82 rai in size, decorated as a garden in a shady atmosphere with large trees, flowers and ornamental plants to serve as a place for relaxation and exercise for local people.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.7890, 100.7428],
  },
  {
    slug: "suan-60-phansa-somdet-phranangchao-phra-borommarachininat",
    nameTh: "สวน 60 พรรษา สมเด็จพระบรมราชินีนาถ",
    nameEn: "Queen's 60th Birthday Park",
    description: "A large community park with space for activities for all ages in a shady atmosphere, cooled by a large pond. It is another beautiful park with good air, suitable for relaxing or exercising with the whole family.",
    fallbackCentroid: [13.8760, 100.5910],
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-somdet-ya-84",
    nameTh: "สวนสมเด็จย่า 84",
    nameEn: "Somdet Ya 84 Park",
    description: "A central park in the area of Lat Phrao Intersection, a place to relax and stretch your legs a bit. Currently, there is a renovation to add a roofed walkway to make it more shady and beautiful. And you can use a skywalk to connect to the Railway Park.",
    openHours: "open 24 hours",
  },
  {
    slug: "suan-thonburirom",
    nameTh: "สวนธนบุรีรมย์",
    nameEn: "Thonburirom Park",
    description: "A green space surrounded by the development of a big city, which still maintains a peaceful, cool and lively atmosphere with tall trees, flowers, creepers, many species of lotus and the sound of birdsong. There are many plants to visit. In the future, it will be developed into a Tropical Herb Garden.",
    openHours: "04:00-21:00",
  },
  {
    slug: "suan-pa-thang-tang-radap-ratchadapisek-wipavadi-rangsit",
    nameTh: "สวนป่าทางตัดระดับรัชดาภิเษก-วิภาวดีรังสิต",
    nameEn: "Ratchadaphisek-Vibhavadi Forest Park",
    description: "The perennial forest park serves as a dust-filtering wall for Bangkokians, reducing temperatures, and providing a recreational area for people to come and do activities and exercise next to the Nong Nam pond building, which is an area on a water storage tank.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-chaloem-phra-kian-phra-bat-somdet-phra-jao-yu-hua-phra-chonnam-phansa-7-rop",
    nameTh: "สวนเฉลิมพระเกียรติพระบาทสมเด็จพระเจ้าอยู่หัว พระชนมพรรษา 7 รอบ",
    nameEn: "King's 7th Cycle Birthday Celebration Park",
    description: "A natural kingdom in Bang Bon area that showcases the royal initiatives of His Majesty King Bhumibol Adulyadej 9 under the concept of 9 Hill Garden, Following in the King's Footsteps and has an area for exercise and relaxation.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-chaloem-phra-kian-80-phansa-phra-bat-somdet-phra-jao-yu-hua-sathorn",
    nameTh: "สวนเฉลิมพระเกียรติ 80 พรรษา พระบาทสมเด็จพระเจ้าอยู่หัว (สาทร)",
    nameEn: "King's 80th Birthday Park (Sathorn)",
    description: "A shady green area with large and small trees, approximately 17 rai, refreshed with a fountain, a waterfall and a waterfall wall, near the Kukrit Institute, which collects and disseminates the works of Professor (Special) Maj. Gen. M.R. Kukrit Pramoj.",
    openHours: "05:00–21:00",
  },
  {
    slug: "suan-chaloem-phra-kian-80-phansa-phra-bat-somdet-phra-jao-yu-hua-bangkok-noi",
    nameTh: "สวนเฉลิมพระเกียรติ 80 พรรษา พระบาทสมเด็จพระเจ้าอยู่หัว (บางกอกน้อย)",
    nameEn: "King's 80th Birthday Park (Bangkok Noi)",
    description: "A green area along the Bangkok Noi Canal that is not only a place for relaxation, admiring nature, exercising and a tourist attraction, but also a public park for learning about botany and culture.",
    openHours: "05:00–21:00",
  },
  {
    slug: "lan-kon-mueang-bkk",
    nameTh: "ลานคนเมือง ศาลากลางกรุงเทพมหานคร",
    nameEn: "City Hall People's Square",
    description: "An area for the public to use, exercise, relax in the evening, watch the sunset and organize various activities, alongside Bangkok City Hall, which acts as a command center for relieving suffering and promoting happiness for Bangkokians.",
    openHours: "05:00–22:00",
    fallbackCentroid: [13.7527, 100.4934],
  },
  {
    slug: "suan-jak-phu-pha-su-mahanatee",
    nameTh: "สวนจากภูผาสู่มหานที",
    nameEn: "Jak Phu Pha Su Mahanatee Park",
    description: "A new public park in the heart of Bangkok, covering an area of 26 rai, located next to Queen Sirikit Park, Kamphaeng Phet 2 Road, Lat Yao Subdistrict, Chatuchak District. This park was created from the concept of From the Mountains to the Great River, presenting a complete forest ecosystem that simulates from the mountains to the river, gathering various species of plants from all over the country.",
    openHours: "05:00–19:00",
  },
  {
    slug: "suan-phanphirom",
    nameTh: "สวนพรรณภิรมย์",
    nameEn: "Phanphirom Park",
    description: "Community park in eastern Bangkok.",
    openHours: "05:00–21:00",
    fallbackCentroid: [13.7240, 100.7790],
  },
]

// Lookup by slug for fast access
export const BMA_META_BY_SLUG = Object.fromEntries(
  BMA_PARKS_META.map((p) => [p.slug, p])
)
